on:
  push:
    tags:
      - '*'

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: build release distributions
        run: |
          cd  device/sdk/python
          python3 -m pip install setuptools
          python3 setup.py sdist

      - name: upload windows dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: device/sdk/python/dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: device/sdk/python/dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: device/sdk/python/dist/
          skip-existing: true
